version: '3.3'
services:
  db:
    image: mysql:8.0
    networks:
      todo-app:
        aliases:
          - mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    deploy:
      replicas: 1
      placement:
        # Only run tasks for service on worker node
        constraints:
          - node.role == worker
    
  app:
    image: untergas/getting-started
    ports:
      - "3001:3000"
    networks:
      todo-app:
        aliases: 
          - app
    # Specify the databse for web service
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    deploy:
      replicas: 5
      placement:
        # Only run tasks for service on worker node
        constraints:
          - node.role == worker


networks:
  todo-app:
    driver: overlay

volumes:
  todo-mysql-data: