---

- hosts: all
  become: true
  tasks:
    - name: install update (Ubuntu)
      apt:
        update_cache: true
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 php package (Ubuntu)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

